name: Generate Comet Contribution Graph

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kiaquila/comet-contribution-graph@v1
        with:
          username: loayayman1515-hue
